
    SELECT DATENAME(MONTH, DATEADD(MONTH, 0, GETDATE())) AS MONTH1 , DATENAME(MONTH, DATEADD(MONTH, 1, GETDATE())) AS MONTH2 ,DATENAME(MONTH, DATEADD(MONTH, 2, GETDATE())) AS MONTH3
    SELECT ((DATEDIFF(MONTH,JoinDate ,'1 August 2023'))*1500) +(DATEDIFF(DAY,JoinDate ,'1 AUGUST 2023')*170) AS TOTALDUE FROM P3 WHERE RID =30
    SELECT DATEDIFF(DAY,GETDATE() ,GETDATE()) FROM P3 WHERE RID =30
    SELECT (DATEDIFF(DAY,,GETDATE()+1 )*170) AS LA FROM L
    WHERE RID = 30
    SELECT (ISNULL(SUM(DATEDIFF(DAY,'1 August 2022','1 August 2023')),0)) *170 AS TLDP FROM L WHERE RID = 30 AND StartDate <= '1 August 2023' AND EndDate >= '1 August 2023' 