SELECT * FROM LEAVE
SELECT * FROM userInfo
SELECT (SELECT COUNT(RID) FROM userInfo) - (SELECT COUNT(RID) FROM LEAVE WHERE LEAVE.STARTDATE <= GETDATE()
AND LEAVE.ENDDATE >= GETDATE()
AND Status = 'ACCEPT') AS ACTIVE_STUDENT